# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/git_repos/DAC/FPGA/DAC/te0726-test_board-vivado_2018.3-build_10_20191211160314/test_board/constraints/vivado_target.xdc

# XDC: E:/git_repos/DAC/FPGA/DAC/te0726-test_board-vivado_2018.3-build_10_20191211160314/test_board/constraints/_i_bitgen_common.xdc

# Block Designs: bd/zsys/zsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys || ORIG_REF_NAME==zsys} -quiet] -quiet

# IP: bd/zsys/ip/zsys_processing_system7_0_0/zsys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_processing_system7_0_0 || ORIG_REF_NAME==zsys_processing_system7_0_0} -quiet] -quiet

# XDC: bd/zsys/zsys_ooc.xdc
